### ISSUE TITLE
Show contributor toplist from earned kredits instead of cash wallet balances

### ISSUE THREAD

**Issue by skddc** [67P/kredits-web#101]

**Comment by bumi** [comment]
we need to think about how/where we get the data. in JS or in the contract. 
and generally we have 3 balances: 
1. confirmed contributions
2. unconfimred contributions
3. token/kredits balance

**Comment by skddc** [comment]
I think if we use the confirmed contributions, we can add the sum for unconfirmed ones dynamically. Or do it the other way around. Ideally we have a tab menu to switch between the two anyway (or an option box to show/hide unconfirmed balance).

**Comment by bumi** [comment]
though it makes sense to somewhere also have a list of kredits owners (which do not need to be contributors)

**Comment by skddc** [comment]
Can be a different view that then loads it when needed.
