### ISSUE TITLE
Asynchronously load initial data

### ISSUE THREAD

**Issue by bumi** [67P/kredits-web#106]
Currently we show a "Loading data from Ethereum..." message until all the data is loaded. 
Is it possible to already render what we got and not wait until everything is loaded. 

Right now this is especially the problem with new IPFS documents which take long to initialy load.

**Comment by skddc** [comment]
Anything is possible, but it will require refactoring all of the loading code, as well as deciding what to show for data that hasn't been loaded yet, so it doesn't show false information either.

**Comment by bumi** [comment]
it works right now for new events, dosn't it? 
when a new contributor/contribution is loaded and it is added to that collection it shows up. 

we could have one spinner like right now, but one that is not blocking the whole interface.

**Comment by skddc** [comment]
I'm not sure what you're saying. Everything I mentioned still has to be done and solved.

> we could have one spinner like right now, but one that is not blocking the whole interface.

You can have either one or the other. You can't have a single blocking spinner, but not block anything. The events that come in afterwards manipulate existing collections, and there's no loading indicator. Neither is there any data missing in between the events.

**Comment by galfert** [comment]
Maybe we can show [skeleton objects](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a) for some elements that are still loading.

**Comment by fsmanuel** [comment]
We need to redo the loading now that we have pagination. Maybe we can put an ember data adapter together to fetch the records. Not sure how you like ember data but it could help to resolve the relationships...

**Comment by bumi** [comment]
The sequential loading of IPFS data is a problem and for example right now I can not open the page because it is waiting for this request (IPFS hash of a new contribution): 
https://ipfs.kosmos.org:5444/api/v0/cat?arg=QmcMFzCHQ9j4gNEFTMwKxbmzEZLP4WJc7zS36HpyLtTS9s&stream-channels=true

also nginx times out after 30(?) seconds but ipfs regularly takes longer, maybe we can increase that timout? @gregkare 
If we have that timeout the page silently breaks and the "Loading data from Ethereum... " is there forever.

**Comment by skddc** [comment]
Closing this, since we implemented caching, and asynchronous loading.
