### ISSUE TITLE
Error when selecting "Special" in manual contribution form

### ISSUE THREAD

**Issue by galfert** [67P/kredits-web#125]
When choosing "Special" for the contribution kind, it shows "Community" as selected instead. And when trying to submit the form, it shows this error in the console:

```
code: 1
dataPath: "/kind"
message: "No enum match for: "special""
params:
value: ""special""
schemaPath: "/properties/kind/type"
subErrors: null
```

**Comment by skddc** [comment]
Means the schemas lib is not the latest version most likely.

**Comment by skddc** [comment]
Do you get this error locally? Because it's up to date in `kredits-contracts` and I'm rather sure I tested it manually.

**Comment by galfert** [comment]
No, I got that on https://kredits.kosmos.org when trying to add the call participations. I must have clicked the "Special" kind by accident at first and didn't notice, because the field was showing "Community" afterwards.
