### ISSUE TITLE
Improve UI for small screens

### ISSUE THREAD

**Issue by skddc** [67P/kredits-web#163]
Various issues since most recent additions haven't been optimized for small screens yet.

E.g. the topbar:

![Screenshot from 2019-11-17 14-10-36](https://user-images.githubusercontent.com/842/69007887-27e58200-0944-11ea-8abc-d8497b17bac4.png)

**Comment by bumi** [comment]
I think this is done?!

**Comment by skddc** [comment]
Yup. We can open new issues for other mobile optimizations.
