### ISSUE TITLE
Load contributions from Contribution contract/storage

### ISSUE THREAD

**Issue by skddc** [67P/kredits-web#20]
<del>As we'll lose the proposals themselves every time we update the Kredits contract, we need to show recent/past contributions from the Token contract data instead.

@bumi I'm not quite sure how we can implement this. Could you provide a rough outline of we'd have to change?</del>

Update: we're in the process of implementing ERC721 tokens for contributions, so all data will move to a Contribution contract/storage. See https://github.com/67P/kredits-contracts/issues/52

**Comment by skddc** [comment]
Note: we need to use the Token contract events for this.

**Comment by skddc** [comment]
@fsmanuel @bumi Is this already solved with your changes by any chance?

**Comment by bumi** [comment]
nope, not yet. 

fyi. was also thinking about looking into the [ERC721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) non-fungible token standard to see if that could be helpful for our case... which would mean one gets one fungible ERC20 token that can be transferred and one erc721 non-fungible token that represents the contribution. 
But even though this might be a bit more flexible and a bit more the ethereum-way of doing it, it might be more complicated.

**Comment by skddc** [comment]
> was also thinking about looking into the ERC721 non-fungible token standard to see if that could be helpful for our case... which would mean one gets one fungible ERC20 token that can be transferred and one erc721 non-fungible token that represents the contribution.

From what I see from their doc, those are also transferable though. In any case, this issue was about the contribution history, not the leaderboard. But yer, for the leaderboard we need to show the tokens issued instead of the tokens currently held.

**Comment by skddc** [comment]
The situation here might have changed, because the proposals are not destroyed anymore. Correct, @bumi?
