### ISSUE TITLE
Sometimes the wrong number of votes is shown

### ISSUE THREAD

**Issue by galfert** [67P/kredits-web#24]
When voting for a proposal and it moves to the closed proposals section, I often see the number of votes to be "3/2 votes". After reloading the browser, it's correct again with "2/2 votes".

Right now, there also is one open proposal that shows "2/2 votes":

![screen shot 2017-06-30 at 11 23 59](https://user-images.githubusercontent.com/843/27729566-afa8f922-5d86-11e7-942e-1fbe322525ce.png)

**Comment by skddc** [comment]
That's from events from before the pageload that are emitted by web3 anyway.

**Comment by galfert** [comment]
Ah, ok. Thanks for the info.

**Comment by skddc** [comment]
This should be fixed already.
