### ISSUE TITLE
More cleanup before we extract the kredits module

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-web#43]
- [ ] Rename our `Kredits` class to `Organization` (at least in the service set it as organization and an alias org)
- [x] Rename `contributor.address` to `contributor.account`
- [x] Rename `proposal.creatorAddress` to `proposal.creator` or `proposal.creatorAccount`
- [ ] Use `RSVP.map` if we can
- [ ] Resolve `TODO`s in kredits module and service

**Comment by bumi** [comment]
regarding `proposal.creator`: we could also change the name in the smart contract to `creatorAddress` might be better because then we always use `*Id` or `*Address` for such fields. what do you think?

**Comment by bumi** [comment]
naming updates in: #45

**Comment by bumi** [comment]
the only todo that is missing in the module is the JSON schema validation. I've created an issue for that #46 as I think that one is too big. (and I don't want to do it right now)

**Comment by skddc** [comment]
It's actually super simple using `tv4`. Basically just a single function call.

**Comment by skddc** [comment]
This looks outdated, as the module is already extracted.
