### ISSUE TITLE
Wallet unlock check not working anymore

### ISSUE THREAD

**Issue by skddc** [67P/kredits-web#64]
In master, checking for an unlocked metamask wallet is currently broken: when you have Metamask enabled, and are on Kovan, but it's still locked, the app will just break with an exception saying it can't find the Contributors contract address in the registry.

**Comment by fsmanuel** [comment]
I'll look into that tomorrow/the day after:
- [ ] The page should load without any wallet/metamask
- [ ] The page should load with locked wallet/metamask
- [ ] Make sure Loading indicator works #60

**Comment by bumi** [comment]
slightly related is #61

**Comment by bumi** [comment]
have a look at #67 first! it seems it solves some problem there..

**Comment by fsmanuel** [comment]
I'm closing this as it is fixed by #67
