### ISSUE TITLE
Errors when opening

### ISSUE THREAD

**Issue by galfert** [67P/kredits-web#85]
When opening https://kredits.kosmos.org with Metamask running, I get the following errors in the console:

![kredits_error](https://user-images.githubusercontent.com/843/54268458-82d80580-457b-11e9-9d95-9ada8cc29ec1.png)

**Comment by skddc** [comment]
Sounds like you're not on Kovan.

**Comment by galfert** [comment]
I'm on Kovan.

When my Metamask is locked, a request to ipfs.kosmos.org is timing out atm. So that might also be the reason for this error.

**Comment by skddc** [comment]
For posterity: solved it during a call. It was me having created the object in local IPFS, and server not being able to fetch that from me.

**Comment by galfert** [comment]
That fixed the timeout. But I'm still getting the same error when Metamask is unlocked.

**Comment by galfert** [comment]
This seems to be a Chrome only problem.

To make it work, you have to change the extension setting for "Site access" to "On all sites". The default is "On click".

![metamask](https://user-images.githubusercontent.com/843/55472681-0336d700-560d-11e9-81c6-a90674962628.png)

**Comment by skddc** [comment]
It should also work with "on specific sites", but you probably have to add more than just the kredits-web domains (e.g. Infura's API domain perhaps).

**Comment by bumi** [comment]
@galfert @gregkare do you still have issues with the latest changes (not yet deployed)

**Comment by skddc** [comment]
I think we can close this, as it's from before upgrading provider support, which was tested and merged.
