### ISSUE TITLE
Support new metamask privacy mode

### ISSUE THREAD

**Issue by bumi** [67P/kredits-web#87]
Seems the metamask privacy mode has become default. Which means we have to request access to the metamask accounts first using `provider.enable()`

> "ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 for complete information and up-to-date example code"

**Comment by skddc** [comment]
I'm having a stab at this.
